In [41]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os 
os.getcwd()

'c:\\Users\\hamoud\\Desktop\\Fraud_detection'

In [42]:
data = pd.read_csv("creditcard.csv")
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [43]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

PREPROCESSING SETUP:

From the small EDA that we have donr, we noticed that there is a lot of outliers in the Amount coulumn, and in the preprocessing part, we cant use standard scaler on it since standard scaler is heavily impacted by outliers. So, we are going to use RobustScaler which is resistant to extreme values. (same with Time column)

In [44]:
from sklearn.model_selection import train_test_split
X= data.drop(columns="Class")
y= data["Class"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify = y)

In [45]:
from sklearn.preprocessing import RobustScaler
amount_scaler = RobustScaler()
time_scaler = RobustScaler()
X_train['scaled_amount'] = amount_scaler.fit_transform(X_train[['Amount']])
X_train['scaled_time'] = time_scaler.fit_transform(X_train[['Time']])
X_test['scaled_amount'] = amount_scaler.transform(X_test[['Amount']])
X_test['scaled_time'] = time_scaler.transform(X_test[['Time']])

In [46]:
X_train = X_train.drop(columns=['Amount','Time'])
X_test = X_test.drop(columns=['Amount','Time'])

In [47]:
X_train.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,scaled_amount,scaled_time
count,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,...,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000,227845.000000
mean,-0.000444,0.001430,0.001966,-0.001225,0.003783,-0.000190,0.001058,0.000054,0.001339,-0.000818,...,-0.000028,-0.000527,0.000454,-0.000244,0.000512,0.000166,-0.000061,0.000044,0.923765,0.118912
std,1.947393,1.644107,1.504254,1.416455,1.360002,1.325614,1.208072,1.190022,1.098943,1.088808,...,0.732173,0.724524,0.612658,0.605794,0.520796,0.481974,0.396942,0.323459,3.386361,0.557533
min,-56.407510,-72.715728,-33.680984,-5.683171,-42.147898,-26.160506,-43.557242,-73.216718,-13.320155,-24.588262,...,-34.830382,-10.933144,-36.666000,-2.836627,-8.696627,-2.534330,-9.895244,-9.617915,-0.307692,-0.993581
25%,-0.920978,-0.597493,-0.889735,-0.849285,-0.690187,-0.768969,-0.552676,-0.208827,-0.641118,-0.536666,...,-0.228591,-0.542743,-0.161705,-0.355041,-0.316706,-0.327277,-0.070787,-0.052961,-0.230070,-0.358243
50%,0.014510,0.066262,0.178063,-0.022962,-0.053208,-0.274658,0.040320,0.022379,-0.050771,-0.093632,...,-0.029798,0.005195,-0.010974,0.040845,0.017068,-0.051258,0.001588,0.011266,0.000000,0.000000
75%,1.314932,0.805070,1.028662,0.743300,0.614515,0.397710,0.571703,0.328024,0.599040,0.453374,...,0.185659,0.526688,0.147375,0.439789,0.351316,0.241421,0.091361,0.078241,0.769930,0.641757
max,2.454930,22.057729,4.226108,16.715537,34.801666,22.529298,36.877368,19.587773,10.392889,15.331742,...,27.202839,10.503090,22.528412,4.022866,6.070850,3.517346,12.152401,33.847808,274.608811,1.034113

In [ ]:
X_train_scaled = X_train.copy()  
X_test_scaled = X_test.copy()
y_train = y_train.copy()
y_test = y_test.copy()
train_scaled = X_train_scaled.copy()
train_scaled['Class'] = y_train
test_scaled = X_test_scaled.copy()
test_scaled['Class'] = y_test
train_scaled.to_csv("creditcard_train_scaled.csv", index=False)
test_scaled.to_csv("creditcard_test_scaled.csv", index=False)